server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service-db
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  redis:
    host: localhost
    port: 6379

# =======================================
# JWT SECURITY CONFIGURATION
# =======================================
application:
  security:
    jwt:
      # This is the secret key used to sign and validate JWTs.
      # It MUST be a Base64-encoded string and strong enough for the HS256 algorithm (at least 256 bits).
      # You can generate a new one using: openssl rand -base64 32
      secret-key: "ZXB0V2AgrXXz+qtS4xJXUzNebA3aeRaesIwzaUVyTN8="

      # This is the token expiration time in milliseconds.
      # 86400000 ms = 24 hours
      # 3600000 ms  = 1 hour
      expiration: 86400000