server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-db
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

api:
  prefix: /api/v1/users
